baseURL                   = "https://aselcuktuncer.github.io"
builddrafts                = true
languageCode               = "tr"
canonifyurls               = true
contentdir                 = "content"
layoutdir                  = "layouts"
publishdir                 = "aselcuktuncer.github.io"
enableEmoji                = true
hasCJKLanguage             = true
summaryLength              = 200
Paginate                   = 3
description                ="Ahmet Selçuk Tunçer"
theme                      = "AllinOne"
title                      = "ASelçuk"
# analytics
  googleAnalytics          = "UA-142872222-1"
  disqusShortname		       = "https-aselcuktuncer-github-io"
  mailchimpURL             = "https://github.us4.list-manage.com/subscribe/post?u=c9ba744cd1ec6ed4d81c5fe41&amp;id=441adbc1ef"  
    

pygmentsuseclasses         = true

enableRobotsTXT = true

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.8

[permalinks]
  blog                     = "blog/:year-:month/:slug/"


[taxonomies]
  tag                      = "tags"
  series                   = "series"
  category                 = "categories"


[menu]
  [[menu.main]]
    name                   = "Geziler"
    weight                 = -120
    identifier             = "geziler"
    url                    = "geziler/"  

  [[menu.main]]
    name                   = "Yazılar"
    weight                 = -110
    identifier             = "yazilar"
    url                    = "yazilar/" 

  [[menu.main]]
    name                   = "Hakkımda"
    weight                 = -100
    identifier             = "hakkimda"
    url                    = "hakkimda/"  

 

[params]
  faviconfile              = ""               # from static/ img/zheng.png
  avatar                   = "img/kedos.jpg"             # path to image in static dir e.g img/avatar.png 
  author                   = "ASelçuk"
  description              = ["Merak Et! Risk Al! Keşfet!",  "Bu harika dünyada yaşadığını hisset!"]           # appears in the site header when set to a non-empty string
  welcome_head             = "Merhaba, Dünya!"
  welcome_word             = "Hayat fırtınanın geçmesini beklemek değil, yağmurda dans etmeyi öğrenmektir."

  latestpostscount         = 5                             # how many posts to display on the home page
  bloggroupby              = 'month'
  dateform                 = "Jan 2, 2006"
  dateformfull             = "2006-01-02  Monday  15:04:05"
  noshowreadtime           = false                         # if true, don't show "<x> minutes read" in posts

  # slides
  slidesDirPath            = "themes/AllinOne/static/img/header-slides"    # path to image in local dir (path for hugo)
  slidesDirPathURL         = "img/header-slides"    # path to image in static dir (for static pages)

  # highlighting 
  highlightjs              = true

  # latex
  katex                    = true

  # links
  email                    = "aselcuktuncer@yahoo.com"
  github                   = "https://www.github.com/aselcuktuncer"
  linkedin                 = "https://www.linkedin.com/in/ahmet-selcuk-tuncer-31861b189"
  facebook                 = "https://www.facebook.com/aselcuk.tuncer"
  twitter                  = "https://www.twitter.com/aselcuktuncer_" 
 
  include_rss              = false                          # include RSS <link> tag in <head> and show RSS icon
  enableRobotsTXT          = true
  canonifyURLs             = true
  